const KEY="my-life-os-premium-v1";
let db=load(),page="home",editIndex=null;
const $=id=>document.getElementById(id);
function blank(){return{money:{income:0,fixed:0,savings:0,variableBudget:480,expenses:[]},trades:[],cars:[],recipes:[],wines:[],fitness:{weight:null,workouts:0,measurements:[]},goals:[]}}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||blank()}catch{return blank()}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function euro(n){return new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(Number(n)||0)}
function n(v){return Number(v)||0}
function dt(v){return v?new Intl.DateTimeFormat("it-IT").format(new Date(v+"T00:00:00")):""}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function today(){return new Date().toISOString().slice(0,10)}
function toast(t){$("toast").textContent=t;$("toast").className="show";setTimeout(()=>$("toast").className="",2000)}
const titles={home:"Dashboard",money:"Money",trading:"Trading",car:"Auto",food:"Food & Wine",fitness:"Forma",goals:"Obiettivi"};
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>go(b.dataset.page));
$("menuBtn").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
$("date").textContent=new Intl.DateTimeFormat("it-IT",{dateStyle:"full"}).format(new Date());
function go(p){page=p;document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$("title").textContent=titles[p];render();document.querySelector(".sidebar").classList.remove("open")}
function render(){({home:home,money:money,trading:trading,car:car,food:food,fitness:fitness,goals:goals}[page])()}

function home(){
 const m=db.money,spent=m.expenses.reduce((s,x)=>s+n(x.amount),0),available=n(m.income)-n(m.fixed)-n(m.savings)-spent;
 const pnl=db.trades.reduce((s,x)=>s+n(x.pnl),0),stake=db.trades.reduce((s,x)=>s+n(x.stake),0),roi=stake?pnl/stake*100:0;
 const avg=db.goals.length?Math.round(db.goals.reduce((s,g)=>s+Math.min(100,n(g.current)/Math.max(1,n(g.target))*100),0)/db.goals.length):0;
 const max=Math.max(1,...db.trades.slice(-10).map(x=>Math.abs(n(x.pnl))));
 const bars=db.trades.slice(-10).map(x=>Math.max(5,Math.abs(n(x.pnl))/max*100));
 $("view").innerHTML=`
 <div class="grid g4">
  <div class="card hero"><div class="label">IL TUO MESE</div><div class="big">${euro(available)}</div><div class="muted">disponibilità dopo spese e risparmi</div><div class="quick" style="margin-top:18px"><button class="action" style="background:#ffffff20;color:#fff" onclick="go('money')">Gestisci budget →</button></div></div>
  <div class="card trading-card"><div class="kpi-row"><div class="kpi-icon">↗</div><div><div class="label">TRADING</div><div class="big">${pnl>=0?"+":""}${euro(pnl)}</div></div></div><div class="muted">${db.trades.length} trade · ROI ${roi.toFixed(1)}%</div></div>
  <div class="card blue-card"><div class="kpi-row"><div class="kpi-icon">♥</div><div><div class="label">FORMA</div><div class="big">${db.fitness.weight?db.fitness.weight+" kg":"—"}</div></div></div><div class="muted">${db.fitness.workouts} allenamenti registrati</div></div>
  <div class="card goal-card"><div class="kpi-row"><div class="kpi-icon">★</div><div><div class="label">OBIETTIVI</div><div class="big">${avg}%</div></div></div><div class="muted">progresso medio</div></div>
 </div>
 <div class="section grid g2">
  <div class="card"><div class="section-head"><div><div class="label">TRADING</div><div class="card-title">Andamento recente</div></div><button class="action soft" onclick="go('trading')">Dettagli</button></div>
   ${db.trades.length?`<div class="chart">${bars.map(h=>`<div class="barcol" style="height:${h}%"></div>`).join("")}</div>`:'<div class="empty">Registra alcuni trade per vedere il grafico.</div>'}
  </div>
  <div class="card"><div class="section-head"><div><div class="label">OBIETTIVI</div><div class="card-title">Dove stai andando</div></div><button class="action soft" onclick="go('goals')">Apri</button></div>
   ${db.goals.length?db.goals.slice(0,3).map(goalMini).join(""):'<div class="empty">Aggiungi il tuo primo obiettivo.</div>'}
  </div>
 </div>
 <div class="section grid g3">
  <div class="card money-card"><div class="label">MONEY</div><div class="card-title">Risparmio</div><div class="big">${euro(m.savings)}</div><div class="muted">accantonato questo mese</div></div>
  <div class="card auto-card"><div class="label">AUTO</div><div class="card-title">Costi registrati</div><div class="big">${euro(db.cars.reduce((s,x)=>s+n(x.cost),0))}</div><div class="muted">${db.cars.length} voci</div></div>
  <div class="card wine-card"><div class="label">FOOD & WINE</div><div class="card-title">Il tuo diario</div><div class="stat"><span>Ricette</span><b>${db.recipes.length}</b></div><div class="stat"><span>Vini</span><b>${db.wines.length}</b></div></div>
 </div>`;
}
function goalMini(g){let p=Math.min(100,n(g.current)/Math.max(1,n(g.target))*100);return `<div class="mini"><div class="stat"><b>${esc(g.name)}</b><b>${p.toFixed(0)}%</b></div><div class="progress"><div class="bar" style="width:${p}%"></div></div><div class="goal-meta"><span>${esc(g.unit||"€")}${n(g.current).toLocaleString("it-IT")}</span><span>target ${esc(g.unit||"€")}${n(g.target).toLocaleString("it-IT")}</span></div></div>`}

function money(){
 const m=db.money,spent=m.expenses.reduce((s,x)=>s+n(x.amount),0),avail=n(m.income)-n(m.fixed)-n(m.savings)-spent;
 $("view").innerHTML=`<div class="grid g3">
 <div class="card hero"><div class="label">DISPONIBILITÀ</div><div class="big">${euro(avail)}</div><div class="muted">entrate − fisse − risparmi − spese</div></div>
 <div class="card money-card"><div class="label">ENTRATE</div><div class="big">${euro(m.income)}</div><div class="muted">mese corrente</div></div>
 <div class="card"><div class="label">RISPARMI</div><div class="big">${euro(m.savings)}</div><div class="muted">accantonati</div></div></div>
 <div class="section grid g2"><div class="card"><div class="section-head"><div><div class="label">BUDGET</div><div class="card-title">Impostazioni mese</div></div><button class="action primary" onclick="moneyModal()">Modifica</button></div>
 ${[['Entrate',m.income],['Spese fisse',m.fixed],['Risparmi',m.savings],['Budget variabile',m.variableBudget]].map(x=>`<div class="stat"><span>${x[0]}</span><b>${euro(x[1])}</b></div>`).join("")}
 </div><div class="card"><div class="section-head"><div><div class="label">SPESE</div><div class="card-title">Movimenti</div></div><button class="action colored" onclick="expenseModal()">+ Spesa</button></div>
 ${m.expenses.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Categoria</th><th>Importo</th><th>Data</th><th></th></tr></thead><tbody>${m.expenses.slice().reverse().map((x,i)=>`<tr><td><span class="pill green">${esc(x.category)}</span></td><td>${euro(x.amount)}</td><td>${dt(x.date)}</td><td><button onclick="delExpense(${m.expenses.length-1-i})" class="action soft">×</button></td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">Nessuna spesa registrata.</div>'}
 </div></div>`;
}
function moneyModal(){modal(`<div class="label">MONEY</div><div class="card-title">Budget del mese</div><div class="form-grid"><div class="field"><label>Entrate<input id="mi" type="number" step=".01" value="${n(db.money.income)}"></label></div><div class="field"><label>Spese fisse<input id="mf" type="number" step=".01" value="${n(db.money.fixed)}"></label></div><div class="field"><label>Risparmi<input id="ms" type="number" step=".01" value="${n(db.money.savings)}"></label></div><div class="field"><label>Budget variabile<input id="mv" type="number" step=".01" value="${n(db.money.variableBudget)}"></label></div></div><div class="form-actions"><button class="action primary" onclick="saveMoney()">Salva</button></div>`)}
function saveMoney(){db.money.income=n($("mi").value);db.money.fixed=n($("mf").value);db.money.savings=n($("ms").value);db.money.variableBudget=n($("mv").value);save();closeModal();render();toast("Budget aggiornato")}
function expenseModal(){modal(`<div class="label">MONEY</div><div class="card-title">Nuova spesa</div><div class="form-grid"><div class="field"><label>Categoria<select id="ec"><option>Spesa</option><option>Svago</option><option>Carburante</option><option>Extra</option><option>Casa</option><option>Altro</option></select></label></div><div class="field"><label>Importo<input id="ea" type="number" step=".01"></label></div><div class="field"><label>Data<input id="ed" type="date" value="${today()}"></label></div><div class="field full"><label>Note<input id="en"></label></div></div><div class="form-actions"><button class="action primary" onclick="saveExpense()">Salva</button></div>`)}
function saveExpense(){db.money.expenses.push({category:$("ec").value,amount:n($("ea").value),date:$("ed").value,note:$("en").value});save();closeModal();render();toast("Spesa registrata")}
function delExpense(i){if(confirm("Eliminare la spesa?")){db.money.expenses.splice(i,1);save();render()}}

function trading(){
 let t=db.trades,p=t.reduce((s,x)=>s+n(x.pnl),0),st=t.reduce((s,x)=>s+n(x.stake),0),roi=st?p/st*100:0,w=t.filter(x=>n(x.pnl)>0).length,wr=t.length?w/t.length*100:0;
 let strat={};t.forEach(x=>strat[x.strategy]=(strat[x.strategy]||0)+n(x.pnl));
 $("view").innerHTML=`<div class="grid g4"><div class="card hero"><div class="label">P/L TOTALE</div><div class="big">${p>=0?"+":""}${euro(p)}</div><div class="muted">${t.length} trade registrati</div></div><div class="card trading-card"><div class="label">ROI</div><div class="big">${roi.toFixed(1)}%</div><div class="muted">P/L ÷ stake</div></div><div class="card"><div class="label">WIN RATE</div><div class="big">${wr.toFixed(1)}%</div><div class="muted">${w} trade positivi</div></div><div class="card"><div class="label">MEDIA / TRADE</div><div class="big">${euro(t.length?p/t.length:0)}</div><div class="muted">profitto medio</div></div></div>
 <div class="section-head"><div><div class="label">JOURNAL</div><h2>Trade</h2></div><button class="action primary" onclick="tradeModal()">+ Nuovo trade</button></div>
 <div class="card">${t.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Partita</th><th>Mercato</th><th>Strategia</th><th>Stake</th><th>Entry</th><th>Exit</th><th>P/L</th><th>Aff.</th><th></th></tr></thead><tbody>${t.slice().reverse().map((x,i)=>`<tr><td>${dt(x.date)}</td><td><b>${esc(x.match)}</b></td><td>${esc(x.market)}</td><td><span class="pill purple">${esc(x.strategy)}</span></td><td>${euro(x.stake)}</td><td>${x.entry||"—"}</td><td>${x.exit||"—"}</td><td class="${n(x.pnl)>=0?"green":"red"}"><b>${n(x.pnl)>=0?"+":""}${euro(x.pnl)}</b></td><td>${x.confidence||"—"}/10</td><td><button class="action soft" onclick="tradeModal(${t.length-1-i})">Apri</button></td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">Il journal è vuoto. Registra il primo trade per iniziare a misurare il tuo metodo.</div>'}</div>
 <div class="section grid g2"><div class="card"><div class="label">STRATEGIE</div><div class="card-title">Dove guadagni</div>${Object.entries(strat).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="stat"><span>${esc(k)}</span><b class="${v>=0?"green":"red"}">${v>=0?"+":""}${euro(v)}</b></div>`).join("")||'<div class="empty">Nessun dato.</div>'}</div><div class="card"><div class="label">AFFIDABILITÀ</div><div class="card-title">Segnali 1–10</div>${confStats()}</div></div>`;
}
function confStats(){let g={};db.trades.forEach(x=>{if(!x.confidence)return;let c=x.confidence;g[c]??={n:0,p:0};g[c].n++;g[c].p+=n(x.pnl)});return Object.keys(g).sort((a,b)=>b-a).map(c=>`<div class="stat"><span><b>${c}/10</b> <span class="muted">${g[c].n} trade</span></span><b class="${g[c].p>=0?"green":"red"}">${g[c].p>=0?"+":""}${euro(g[c].p)}</b></div>`).join("")||'<div class="empty">Inserisci l’affidabilità nei trade.</div>'}
function tradeModal(i=null){editIndex=i;let x=i!==null?db.trades[i]:{};modal(`<div class="label">SPORT TRADING</div><div class="card-title">${i===null?"Nuovo trade":"Modifica trade"}</div><div class="form-grid">
<div class="field"><label>Data<input id="td" type="date" value="${x.date||today()}"></label></div><div class="field"><label>Partita<input id="tm" value="${esc(x.match||"")}"></label></div>
<div class="field"><label>Competizione<input id="tc" value="${esc(x.competition||"")}"></label></div><div class="field"><label>Mercato<input id="tmarket" value="${esc(x.market||"Match Odds")}"></label></div>
<div class="field"><label>Strategia<input id="ts" value="${esc(x.strategy||"")}"></label></div><div class="field"><label>Tipo<select id="tt"><option>Back</option><option ${x.type==="Lay"?"selected":""}>Lay</option></select></label></div>
<div class="field"><label>Stake €<input id="tst" type="number" step=".01" value="${x.stake??""}"></label></div><div class="field"><label>Quota ingresso<input id="te" type="number" step=".01" value="${x.entry??""}"></label></div>
<div class="field"><label>Quota uscita<input id="tx" type="number" step=".01" value="${x.exit??""}"></label></div><div class="field"><label>P/L netto €<input id="tp" type="number" step=".01" value="${x.pnl??""}"></label></div>
<div class="field"><label>Affidabilità 1–10<input id="tcf" type="number" min="1" max="10" value="${x.confidence??""}"></label></div><div class="field"><label>Segnale corretto?<select id="tsg"><option>Non valutato</option><option ${x.signal==="Sì"?"selected":""}>Sì</option><option ${x.signal==="No"?"selected":""}>No</option><option ${x.signal==="Parzialmente"?"selected":""}>Parzialmente</option></select></label></div>
<div class="field"><label>Timing corretto?<select id="tti"><option>Non valutato</option><option ${x.timing==="Sì"?"selected":""}>Sì</option><option ${x.timing==="No"?"selected":""}>No</option></select></label></div><div class="field"><label>Esecuzione<input id="tq" value="${esc(x.execution||"")}"></label></div>
<div class="field full"><label>Note<input id="tn" value="${esc(x.note||"")}" placeholder="Contesto, errore, cosa rifarei..."></label></div></div>
<div class="form-actions">${i!==null?'<button class="delete" onclick="delTrade()">Elimina</button>':""}<button class="action primary" onclick="saveTrade()">Salva trade</button></div>`)}
function saveTrade(){let x={date:$("td").value,match:$("tm").value,competition:$("tc").value,market:$("tmarket").value,strategy:$("ts").value,type:$("tt").value,stake:n($("tst").value),entry:n($("te").value),exit:n($("tx").value),pnl:n($("tp").value),confidence:$("tcf").value,signal:$("tsg").value,timing:$("tti").value,execution:$("tq").value,note:$("tn").value};editIndex===null?db.trades.push(x):db.trades[editIndex]=x;save();closeModal();render();toast("Trade salvato")}
function delTrade(){if(confirm("Eliminare questo trade?")){db.trades.splice(editIndex,1);save();closeModal();render()}}

function car(){let total=db.cars.reduce((s,x)=>s+n(x.cost),0),km=db.cars.length?Math.max(...db.cars.map(x=>n(x.km))):0;$("view").innerHTML=`<div class="grid g3"><div class="card auto-card"><div class="label">COSTI</div><div class="big">${euro(total)}</div><div class="muted">${db.cars.length} voci registrate</div></div><div class="card"><div class="label">KM</div><div class="big">${km?km.toLocaleString("it-IT"):"—"}</div><div class="muted">ultimo chilometraggio</div></div><div class="card"><div class="label">FOCUS</div><div class="card-title">Costo/km</div><div class="big">${km?(total/km).toFixed(2):"—"} €</div><div class="muted">sui dati inseriti</div></div></div><div class="section-head"><div><div class="label">DIARIO AUTO</div><h2>Costi & manutenzione</h2></div><button class="action primary" onclick="carModal()">+ Registra</button></div><div class="card">${db.cars.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Voce</th><th>Tipo</th><th>Km</th><th>Costo</th><th>Note</th></tr></thead><tbody>${db.cars.slice().reverse().map(x=>`<tr><td>${dt(x.date)}</td><td>${esc(x.item)}</td><td><span class="pill">${esc(x.type)}</span></td><td>${n(x.km).toLocaleString("it-IT")}</td><td>${euro(x.cost)}</td><td>${esc(x.note)}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">Registra carburante, manutenzione, gomme, assicurazione, bollo e altri costi.</div>'}</div>`}
function carModal(){modal(`<div class="label">AUTO</div><div class="card-title">Nuova voce</div><div class="form-grid"><div class="field"><label>Data<input id="cd" type="date" value="${today()}"></label></div><div class="field"><label>Veicolo<input id="cc" value="Renault Captur"></label></div><div class="field"><label>Voce<input id="ci" placeholder="Tagliando, carburante..."></label></div><div class="field"><label>Tipo<input id="ct" placeholder="Manutenzione"></label></div><div class="field"><label>Km<input id="ck" type="number"></label></div><div class="field"><label>Costo €<input id="cx" type="number" step=".01"></label></div><div class="field full"><label>Note<input id="cn"></label></div></div><div class="form-actions"><button class="action primary" onclick="saveCar()">Salva</button></div>`)}
function saveCar(){db.cars.push({date:$("cd").value,car:$("cc").value,item:$("ci").value,type:$("ct").value,km:n($("ck").value),cost:n($("cx").value),note:$("cn").value});save();closeModal();render();toast("Voce auto salvata")}

function food(){$("view").innerHTML=`<div class="grid g2"><div class="card wine-card"><div class="label">RICETTE</div><div class="big">${db.recipes.length}</div><div class="muted">Il tuo ricettario personale</div><div class="quick" style="margin-top:13px"><button class="action colored" onclick="recipeModal()">+ Ricetta</button></div></div><div class="card"><div class="label">VINI</div><div class="big">${db.wines.length}</div><div class="muted">Assaggi, voti e riacquisti</div><div class="quick" style="margin-top:13px"><button class="action soft" onclick="wineModal()">+ Vino</button></div></div></div><div class="section grid g2"><div class="card"><div class="label">RICETTE RECENTI</div>${db.recipes.length?db.recipes.slice().reverse().map(r=>`<div class="mini"><b>${esc(r.name)}</b><div class="stars">${"★".repeat(n(r.rating))}${"☆".repeat(5-n(r.rating))}</div><div class="muted">${esc(r.note||"")}</div></div>`).join(""):'<div class="empty">Nessuna ricetta.</div>'}</div><div class="card"><div class="label">VINI RECENTI</div>${db.wines.length?db.wines.slice().reverse().map(w=>`<div class="mini"><b>${esc(w.name)}</b> · ${esc(w.region)}<div class="stars">${"★".repeat(n(w.rating))}${"☆".repeat(5-n(w.rating))}</div><div class="muted">${esc(w.buy)} · ${w.price?euro(w.price):"prezzo n/d"}</div></div>`).join(""):'<div class="empty">Nessun vino.</div>'}</div></div>`}
function recipeModal(){modal(`<div class="label">FOOD & WINE</div><div class="card-title">Nuova ricetta</div><div class="form-grid"><div class="field full"><label>Nome<input id="rn"></label></div><div class="field"><label>Voto 1–5<input id="rr" type="number" min="1" max="5" value="5"></label></div><div class="field"><label>Tempo<input id="rt" placeholder="25 min"></label></div><div class="field full"><label>Ingredienti<textarea id="ri" rows="3"></textarea></label></div><div class="field full"><label>Procedimento<textarea id="rp" rows="3"></textarea></label></div><div class="field full"><label>Cosa cambiare la prossima volta<input id="rx"></label></div></div><div class="form-actions"><button class="action primary" onclick="saveRecipe()">Salva</button></div>`)}
function saveRecipe(){db.recipes.push({name:$("rn").value,rating:n($("rr").value),time:$("rt").value,ingredients:$("ri").value,procedure:$("rp").value,note:$("rx").value});save();closeModal();render();toast("Ricetta salvata")}
function wineModal(){modal(`<div class="label">FOOD & WINE</div><div class="card-title">Nuovo vino</div><div class="form-grid"><div class="field full"><label>Vino<input id="wn"></label></div><div class="field"><label>Produttore<input id="wpd"></label></div><div class="field"><label>Regione<input id="wr"></label></div><div class="field"><label>Vitigno<input id="wg"></label></div><div class="field"><label>Annata<input id="wvint"></label></div><div class="field"><label>Prezzo €<input id="wpr" type="number" step=".01"></label></div><div class="field"><label>Voto 1–5<input id="wrt" type="number" min="1" max="5" value="5"></label></div><div class="field"><label>Ricomprerei?<select id="wb"><option>Sì</option><option>No</option><option>Forse</option></select></label></div><div class="field full"><label>Note / abbinamenti<textarea id="wx" rows="3"></textarea></label></div></div><div class="form-actions"><button class="action primary" onclick="saveWine()">Salva</button></div>`)}
function saveWine(){db.wines.push({name:$("wn").value,producer:$("wpd").value,region:$("wr").value,grape:$("wg").value,vintage:$("wvint").value,price:n($("wpr").value),rating:n($("wrt").value),buy:$("wb").value,note:$("wx").value});save();closeModal();render();toast("Vino salvato")}

function fitness(){$("view").innerHTML=`<div class="grid g3"><div class="card blue-card"><div class="label">PESO ATTUALE</div><div class="big">${db.fitness.weight?db.fitness.weight+" kg":"—"}</div><div class="muted">ultimo dato</div></div><div class="card"><div class="label">ALLENAMENTI</div><div class="big">${db.fitness.workouts}</div><div class="muted">sessioni registrate</div></div><div class="card"><div class="label">STORICO</div><div class="big">${db.fitness.measurements.length}</div><div class="muted">misurazioni</div></div></div><div class="section-head"><div><div class="label">PROGRESSI</div><h2>Diario</h2></div><button class="action primary" onclick="fitnessModal()">+ Registra</button></div><div class="card">${db.fitness.measurements.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Peso</th><th>Allenamento</th><th>Note</th></tr></thead><tbody>${db.fitness.measurements.slice().reverse().map(x=>`<tr><td>${dt(x.date)}</td><td><b>${x.weight} kg</b></td><td>${x.workout?"✓":"—"}</td><td>${esc(x.note)}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">Registra peso e allenamenti per creare il tuo storico.</div>'}</div>`}
function fitnessModal(){modal(`<div class="label">FORMA</div><div class="card-title">Nuova registrazione</div><div class="form-grid"><div class="field"><label>Data<input id="fd" type="date" value="${today()}"></label></div><div class="field"><label>Peso kg<input id="fw" type="number" step=".1"></label></div><div class="field"><label>Allenamento<select id="fo"><option>Sì</option><option>No</option></select></label></div><div class="field full"><label>Note<input id="fn"></label></div></div><div class="form-actions"><button class="action primary" onclick="saveFitness()">Salva</button></div>`)}
function saveFitness(){let w=n($("fw").value),wo=$("fo").value==="Sì";db.fitness.weight=w||db.fitness.weight;db.fitness.workouts+=wo?1:0;db.fitness.measurements.push({date:$("fd").value,weight:w||"",workout:wo,note:$("fn").value});save();closeModal();render();toast("Progressi salvati")}

function goals(){$("view").innerHTML=`<div class="section-head"><div><div class="label">DIREZIONE</div><h2>I tuoi obiettivi</h2></div><button class="action primary" onclick="goalModal()">+ Obiettivo</button></div><div class="grid g3">${db.goals.length?db.goals.map((g,i)=>{let p=Math.min(100,n(g.current)/Math.max(1,n(g.target))*100);return `<div class="card goal"><div class="goal-top"><span class="goal-name">${esc(g.name)}</span><span class="goal-pct">${p.toFixed(0)}%</span></div><div class="progress"><div class="bar" style="width:${p}%"></div></div><div class="goal-meta"><span>${esc(g.unit||"€")}${n(g.current).toLocaleString("it-IT")}</span><span>${esc(g.unit||"€")}${n(g.target).toLocaleString("it-IT")}</span></div><div class="quick" style="margin-top:13px"><button class="action soft" onclick="goalModal(${i})">Modifica</button><button class="action" style="background:#fff0f2;color:#a63c51" onclick="delGoal(${i})">Elimina</button></div></div>`}).join(""):'<div class="card empty">Nessun obiettivo. Aggiungi fondo auto, emergenza, investimenti, formazione o obiettivi personali.</div>'}</div>`}
function goalModal(i=null){editIndex=i;let g=i!==null?db.goals[i]:{};modal(`<div class="label">OBIETTIVI</div><div class="card-title">${i===null?"Nuovo obiettivo":"Modifica obiettivo"}</div><div class="form-grid"><div class="field full"><label>Nome<input id="gn" value="${esc(g.name||"")}"></label></div><div class="field"><label>Categoria<input id="gc" value="${esc(g.category||"Finanze")}"></label></div><div class="field"><label>Unità<input id="gu" value="${esc(g.unit||"€")}"></label></div><div class="field"><label>Valore attuale<input id="gv" type="number" step=".01" value="${g.current??0}"></label></div><div class="field"><label>Target<input id="gt" type="number" step=".01" value="${g.target??100}"></label></div></div><div class="form-actions">${i!==null?'<button class="delete" onclick="delGoal(editIndex)">Elimina</button>':""}<button class="action primary" onclick="saveGoal()">Salva</button></div>`)}
function saveGoal(){let g={name:$("gn").value,category:$("gc").value,unit:$("gu").value,current:n($("gv").value),target:n($("gt").value)};editIndex===null?db.goals.push(g):db.goals[editIndex]=g;save();closeModal();render();toast("Obiettivo salvato")}
function delGoal(i){if(confirm("Eliminare l'obiettivo?")){db.goals.splice(i,1);save();closeModal();render()}}

function modal(html){$("modalBody").innerHTML=html;$("modal").classList.remove("hidden")}
function closeModal(){$("modal").classList.add("hidden");editIndex=null}
$("close").onclick=closeModal;$("modal").onclick=e=>{if(e.target.classList.contains("modal-bg"))closeModal()};
$("exportBtn").onclick=()=>{let b=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="my-life-os-backup.json";a.click();URL.revokeObjectURL(a.href)};
$("importInput").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();render();toast("Backup ripristinato")}catch{alert("Backup non valido")}e.target.value=""};r.readAsText(f)};
$("resetBtn").onclick=()=>{if(confirm("Azzera tutti i dati di My Life OS?")){db=blank();save();render();toast("Dati azzerati")}};
render();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
